name: Update README with API Data

on:
  # push
  schedule:
    - cron: '* * * * *' # Runs every minute

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:

    # - name: Install curl and jq
    #   run: |
    #     apt-get update
    #     apt-get install -y curl jq

    - name: Fetch OHLCV data
      env:
        CHAIN: eth #Specify the chain eth/bsc/polygon_pos/avax/movr/cro/one/boba/ftm/bch, check entire list: https://api.geckoterminal.com/api/v2/networks
        POOL: '0xb125aa15Ad943D96e813E4A06d0c34716F897e26' #Specify the pool address
        TIMEFRAME: day #Specify the timeframe day/hour/minute
        AGGREGATE: 1 #Specify the aggregate options - day: [1], hour: [1, 4, 12] minute: [1, 5, 15]
        LIMIT: 1000 #Specify the limit 100 - 1000
      run: |
        response=$(curl -s 'https://api.geckoterminal.com/api/v2/networks/${CHAIN}/pools/${POOL}/ohlcv/${TIMEFRAME}?aggregate=${AGGREGATE}&limit=${LIMIT}')
        dates=$(echo "$response" | jq -r '.data.attributes.ohlcv_list[] | .[0]' | xargs -I {} date -d @{} +%Y-%m-%d | paste -sd, -)
        closes=$(echo "$response" | jq -r '.data.attributes.ohlcv_list[] | .[4]' | paste -sd, -)

        chart=$(cat <<EOF
        \```mermaid
        xychart-beta
            title "Daily Closing Prices"
            x-axis [${dates}]
            y-axis "Price (in USD)"
            line [${closes}]
        \```
        EOF
        )
        echo -e "## Daily Closing Prices\n\n${chart}" > README.md
        echo "Updated README.md content:"
        cat README.md

    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git remote set-url origin https://github-actions:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
        git add README.md
        git commit -m "Update README with latest DEX data" || echo "No changes to commit"
        git push